services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - proxy
    expose:
      - "${SERVER_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evolution-api.entrypoints=websecure"
      - "traefik.http.routers.evolution-api.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.evolution-api.loadbalancer.server.port=${SERVER_PORT}"
      
      # Security Middleware 
      - "traefik.http.middlewares.secure-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.secure-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.secure-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.secure-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.secure-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.secure-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.secure-headers.headers.stsSeconds=31536000"
     
      # Apply middlewares to router
      - "traefik.http.routers.evolution-api.middlewares=secure-headers"
      
      # Add TLS
      - "traefik.http.routers.evolution-api.tls=true"
      - "traefik.http.routers.evolution-api.tls.certresolver=le"

volumes:
  evolution_instances:

networks:
  proxy:
    external: true